import type { AppLocale } from "@/i18n/routing"
import { localizeEnglishContent } from "@/i18n/content"

export type LegalSection = {
  title: string
  body: string[]
}

type LegalPage = {
  eyebrow: string
  title: string
  lede: string
  breadcrumb: string
  sections: LegalSection[]
}

const privacy: Record<"en" | "tr", LegalPage> = {
  en: {
    eyebrow: "Legal",
    title: "Privacy Policy",
    lede: "Effective July 13, 2026. This policy explains Aurict's current privacy posture, BYOK model, third-party dependencies, and analytics choices.",
    breadcrumb: "Privacy",
    sections: [
      { title: "1. Current data collection", body: ["Aurict does not intentionally collect product telemetry, chat content, repository contents, API keys, prompts, or generated files through the public website or the open-source CLI by default.", "If you choose to use account, authentication, device login, support, waitlist, or similar features, the information you submit or authorize may be processed only as needed to provide that feature.", "The public website uses Google Analytics 4 for aggregated usage measurement. Advertising features and advertising personalization are disabled."] },
      { title: "2. Analytics and your choices", body: ["On your first visit, Aurict asks whether you allow analytics storage. If you allow it, Google Analytics may use analytics cookies to measure pages and interactions so we can improve the website.", "If you decline, Aurict keeps analytics storage disabled. Google Consent Mode may send a cookieless, aggregate measurement signal that helps us understand that a visit occurred; it does not enable an Aurict analytics cookie or advertising personalization.", "You can change this choice at any time using the cookie preference control at the lower-left of the website. Your choice is stored in your browser."] },
      { title: "3. Bring Your Own Key model", body: ["Aurict is designed around BYOK: Bring Your Own Key. You are responsible for the API keys, model providers, billing accounts, and third-party services you connect.", "Model provider keys should be handled as secrets. Do not share them publicly, commit them to repositories, paste them into untrusted contexts, or expose them to unauthorized users.", "When you use external model providers, those providers may process your prompts, files, outputs, metadata, and account data under their own policies and terms."] },
      { title: "4. Authentication and third-party services", body: ["Aurict may use third-party infrastructure such as Firebase, Google, Google Analytics, GitHub, hosting providers, package registries, and model providers to deliver authentication, measurement, device login, downloads, releases, or integrations.", "Those services may receive technical information such as account identifiers, email addresses, authentication tokens, IP addresses, device metadata, logs, or request metadata depending on the feature you use and the choices you make.", "Aurict does not control third-party privacy practices. You should review the policies of any provider you connect to Aurict."] },
      { title: "5. Local-first and open-source workflows", body: ["The open-source Aurict CLI is intended to run primarily in your own environment. Local configuration, project files, session data, and provider keys may remain on your device or infrastructure depending on how you configure the software.", "If you connect MCP servers, cloud accounts, databases, browsers, GitHub, or other tools, data may flow through those systems according to your configuration.", "You are responsible for understanding what tools you enable and what data those tools can access."] },
      { title: "6. Future data collection may change", body: ["Aurict may add optional or required data collection in the future, including but not limited to account data, billing data, crash reports, abuse prevention logs, security logs, analytics, waitlist/contact information, device login metadata, or product telemetry.", "If data practices materially change, Aurict may update this Privacy Policy and may provide notice through the website, application, repository, release notes, or other reasonable channels.", "Continued use after an update may be treated as acceptance of the updated policy where permitted by law."] },
      { title: "7. Security", body: ["Aurict aims to minimize unnecessary data collection. This follows a practical security principle: do not collect or retain sensitive information unless there is a legitimate product or operational need.", "No software, website, network, or third-party provider is perfectly secure. You are responsible for securing your own devices, repositories, API keys, provider accounts, and deployment environments.", "If you discover a vulnerability, report it responsibly through the repository or the contact channel provided by the project owner."] },
      { title: "8. Policy ownership and changes", body: ["Aurict and the repository owner reserve the right to update, replace, expand, narrow, suspend, or remove this Privacy Policy at any time.", "This policy is provided to explain the current intended privacy posture of the project. It is not legal advice and does not create contractual rights beyond those required by applicable law."] },
    ],
  },
  tr: {
    eyebrow: "Hukuk",
    title: "Gizlilik Politikası",
    lede: "Yürürlük: 13 Temmuz 2026. Bu politika Aurict'in mevcut gizlilik yaklaşımını, BYOK modelini, üçüncü taraf bağımlılıklarını ve analitik tercihlerini açıklar.",
    breadcrumb: "Gizlilik",
    sections: [
      { title: "1. Mevcut veri toplama", body: ["Aurict; herkese açık web sitesi veya açık kaynak CLI üzerinden varsayılan olarak ürün telemetrisi, sohbet içeriği, depo içeriği, API anahtarı, istem ya da üretilmiş dosya toplamayı amaçlamaz.", "Hesap, kimlik doğrulama, cihaz girişi, destek, bekleme listesi veya benzer özellikleri kullanmayı seçerseniz; gönderdiğiniz ya da yetkilendirdiğiniz bilgiler yalnızca o özelliği sunmak için gereken ölçüde işlenebilir.", "Herkese açık web sitesi, toplu kullanım ölçümü için Google Analytics 4 kullanır. Reklam özellikleri ve reklam kişiselleştirmesi kapalıdır."] },
      { title: "2. Analitik ve tercihleriniz", body: ["İlk ziyaretinizde analitik depolamaya izin verip vermediğinizi sorarız. İzin verirseniz Google Analytics, web sitesini iyileştirmemiz için ziyaret edilen sayfaları ve etkileşimleri ölçmek üzere analitik çerezleri kullanabilir.", "Reddederseniz Aurict analitik depolamayı kapalı tutar. Google Consent Mode, bir ziyaretin gerçekleştiğini anlamamıza yardımcı olmak için çerezsiz ve toplu bir ölçüm sinyali gönderebilir; bu, Aurict analitik çerezini veya reklam kişiselleştirmesini etkinleştirmez.", "Bu tercihi sitenin sol altındaki çerez tercihi denetiminden dilediğiniz zaman değiştirebilirsiniz. Tercihiniz tarayıcınızda saklanır."] },
      { title: "3. Kendi Anahtarını Getir modeli", body: ["Aurict, BYOK (Bring Your Own Key / Kendi Anahtarını Getir) etrafında tasarlanmıştır. Bağladığınız API anahtarlarından, model sağlayıcılarından, faturalama hesaplarından ve üçüncü taraf hizmetlerden siz sorumlusunuz.", "Model sağlayıcı anahtarları gizli bilgi olarak ele alınmalıdır. Bunları herkese açık biçimde paylaşmayın, depolara işlemeyin, güvenilmeyen bağlamlara yapıştırmayın ve yetkisiz kişilere açmayın.", "Harici model sağlayıcılarını kullandığınızda bu sağlayıcılar; kendi politika ve şartları çerçevesinde istemlerinizi, dosyalarınızı, çıktılarınızı, meta verilerinizi ve hesap verilerinizi işleyebilir."] },
      { title: "4. Kimlik doğrulama ve üçüncü taraf hizmetleri", body: ["Aurict; kimlik doğrulama, ölçümleme, cihaz girişi, indirmeler, sürümler veya entegrasyonlar için Firebase, Google, Google Analytics, GitHub, barındırma sağlayıcıları, paket kayıtları ve model sağlayıcıları gibi üçüncü taraf altyapıları kullanabilir.", "Kullandığınız özelliğe ve yaptığınız tercihlere bağlı olarak bu hizmetler hesap kimlikleri, e-posta adresleri, kimlik doğrulama belirteçleri, IP adresleri, cihaz meta verileri, günlükler veya istek meta verileri gibi teknik bilgileri alabilir.", "Aurict üçüncü tarafların gizlilik uygulamalarını denetlemez. Aurict'e bağladığınız her sağlayıcının politikasını incelemelisiniz."] },
      { title: "5. Yerel öncelikli ve açık kaynak iş akışları", body: ["Açık kaynak Aurict CLI, öncelikle kendi ortamınızda çalışmak üzere tasarlanmıştır. Yerel yapılandırma, proje dosyaları, oturum verileri ve sağlayıcı anahtarları; yazılımı nasıl yapılandırdığınıza bağlı olarak cihazınızda veya altyapınızda kalabilir.", "MCP sunucuları, bulut hesapları, veritabanları, tarayıcılar, GitHub veya başka araçlar bağlarsanız; veriler yapılandırmanıza bağlı olarak bu sistemlerden akabilir.", "Hangi araçları etkinleştirdiğinizi ve bu araçların hangi verilere erişebileceğini anlamaktan siz sorumlusunuz."] },
      { title: "6. Gelecekte veri toplama değişebilir", body: ["Aurict gelecekte hesap verisi, faturalama verisi, çökme raporu, kötüye kullanımı önleme günlükleri, güvenlik günlükleri, analitik, bekleme listesi/iletişim bilgisi, cihaz girişi meta verisi veya ürün telemetrisi dahil ancak bunlarla sınırlı olmamak üzere isteğe bağlı ya da zorunlu veri toplama ekleyebilir.", "Veri uygulamaları esaslı biçimde değişirse Aurict bu Gizlilik Politikasını güncelleyebilir ve web sitesi, uygulama, depo, sürüm notları veya makul başka kanallarla bildirim sağlayabilir.", "Güncellemeden sonra kullanımın sürdürülmesi, hukukun izin verdiği yerde güncellenmiş politikayı kabul olarak değerlendirilebilir."] },
      { title: "7. Güvenlik", body: ["Aurict gereksiz veri toplamayı en aza indirmeyi hedefler. Bu pratik bir güvenlik ilkesidir: meşru bir ürün veya operasyon ihtiyacı yoksa hassas bilgiyi toplamayın ya da saklamayın.", "Hiçbir yazılım, web sitesi, ağ veya üçüncü taraf sağlayıcı bütünüyle güvenli değildir. Kendi cihazlarınızı, depolarınızı, API anahtarlarınızı, sağlayıcı hesaplarınızı ve dağıtım ortamlarınızı korumaktan siz sorumlusunuz.", "Bir güvenlik açığı bulursanız bunu depo veya proje sahibinin sunduğu iletişim kanalı üzerinden sorumlu biçimde bildirin."] },
      { title: "8. Politikanın sahipliği ve değişiklikler", body: ["Aurict ve depo sahibi bu Gizlilik Politikasını dilediği anda güncelleme, değiştirme, genişletme, daraltma, askıya alma veya kaldırma hakkını saklı tutar.", "Bu politika projenin mevcut hedeflenen gizlilik yaklaşımını açıklamak için sağlanır. Hukukun gerektirdiği hakların ötesinde hukuki tavsiye değildir ve sözleşmesel hak oluşturmaz."] },
    ],
  },
}

const terms: Record<"en" | "tr", LegalPage> = {
  en: {
    eyebrow: "Legal", title: "Terms of Use", breadcrumb: "Terms", lede: "Effective July 2, 2026. These terms define the rules for using Aurict, including BYOK responsibilities, security boundaries, account flows, and future policy changes.",
    sections: [
      { title: "1. Acceptance", body: ["By accessing the Aurict website, using the Aurict software, installing the CLI, using the mobile app, connecting a provider, or interacting with related services, you agree to these Terms of Use.", "If you do not agree, do not use Aurict."] },
      { title: "2. Open-source software and license", body: ["Aurict is provided as open-source software under the license stated in the repository, currently GNU Affero General Public License v3 for the core project unless a specific file, package, or component states otherwise.", "The open-source license governs your rights to copy, modify, distribute, and use the source code. These Terms govern your use of the website, hosted features, account flows, device login, documentation, branding, and related services."] },
      { title: "3. BYOK responsibility", body: ["Aurict uses a Bring Your Own Key model. You are responsible for the API keys, model accounts, billing, quotas, provider terms, and third-party services you connect.", "Aurict does not control the pricing, output quality, availability, retention, moderation, or privacy behavior of external model providers.", "You are responsible for protecting your keys and for all usage, charges, prompts, outputs, and consequences that occur through your connected providers."] },
      { title: "4. AI output and professional judgment", body: ["Aurict may generate, transform, summarize, or execute technical instructions using AI models. Outputs may be incomplete, incorrect, insecure, outdated, or unsuitable for your use case.", "You are responsible for reviewing, testing, validating, and approving outputs before relying on them.", "Aurict does not provide legal, medical, financial, compliance, or professional advice."] },
      { title: "5. Security and cybersecurity features", body: ["Aurict may include security analysis, code review, sandbox execution, command classification, MCP integrations, browser workflows, and optional cybersecurity tooling.", "You may use these features only on systems, accounts, networks, repositories, devices, or targets that you own or are explicitly authorized to test.", "You must not use Aurict for unauthorized access, credential theft, malware, persistence, evasion, data exfiltration, harassment, abuse, or any illegal activity."] },
      { title: "6. Accounts, device login, and access", body: ["Aurict may provide account, authentication, browser login, device approval, or session control features. You are responsible for keeping your account and devices secure.", "Aurict and the repository owner may restrict, suspend, revoke, change, or discontinue access to hosted features where necessary for security, abuse prevention, maintenance, legal compliance, or product direction."] },
      { title: "7. Data practices may change", body: ["Aurict does not currently intend to collect product telemetry, chat content, repository contents, prompts, generated files, or API keys by default through the public website or open-source CLI.", "This may change in the future. Aurict may introduce data collection for accounts, billing, telemetry, crash reporting, analytics, security, fraud prevention, abuse prevention, or product operation.", "Future use may be subject to updated privacy terms, consent flows, notices, configuration options, or provider-specific requirements."] },
      { title: "8. Changes to these Terms", body: ["Aurict and the repository owner reserve the right to update, replace, expand, narrow, suspend, or remove these Terms at any time.", "Changes may be posted on the website, in the repository, in release notes, or through other reasonable channels. Continued use after changes are posted may be treated as acceptance of the updated Terms where permitted by law."] },
      { title: "9. Disclaimer and limitation of liability", body: ["Aurict is provided as-is and as-available, without warranties of any kind to the maximum extent permitted by law.", "Aurict, its repository owner, maintainers, contributors, and related parties are not liable for lost profits, lost data, provider charges, security incidents, business interruption, model errors, unauthorized use, or indirect, incidental, special, consequential, or punitive damages arising from your use of Aurict."] },
    ],
  },
  tr: {
    eyebrow: "Hukuk", title: "Kullanım Koşulları", breadcrumb: "Koşullar", lede: "Yürürlük: 2 Temmuz 2026. Bu koşullar; BYOK sorumlulukları, güvenlik sınırları, hesap akışları ve gelecekteki politika değişiklikleri dahil Aurict kullanım kurallarını tanımlar.",
    sections: [
      { title: "1. Kabul", body: ["Aurict web sitesine erişerek, Aurict yazılımını kullanarak, CLI'ı kurarak, mobil uygulamayı kullanarak, bir sağlayıcı bağlayarak veya ilgili hizmetlerle etkileşim kurarak bu Kullanım Koşullarını kabul etmiş olursunuz.", "Kabul etmiyorsanız Aurict'i kullanmayın."] },
      { title: "2. Açık kaynak yazılım ve lisans", body: ["Aurict, depoda belirtilen lisans altında açık kaynak yazılım olarak sunulur. Belirli bir dosya, paket veya bileşen aksini belirtmedikçe çekirdek proje için mevcut lisans GNU Affero General Public License v3'tür.", "Açık kaynak lisansı kaynak kodunu kopyalama, değiştirme, dağıtma ve kullanma haklarınızı yönetir. Bu Koşullar; web sitesi, barındırılan özellikler, hesap akışları, cihaz girişi, dokümantasyon, marka ve ilgili hizmetleri kullanımınızı yönetir."] },
      { title: "3. BYOK sorumluluğu", body: ["Aurict, Kendi Anahtarını Getir modelini kullanır. Bağladığınız API anahtarları, model hesapları, faturalama, kotalar, sağlayıcı koşulları ve üçüncü taraf hizmetlerden siz sorumlusunuz.", "Aurict, harici model sağlayıcılarının fiyatlandırmasını, çıktı kalitesini, kullanılabilirliğini, saklama, moderasyon veya gizlilik davranışını denetlemez.", "Anahtarlarınızı korumaktan ve bağlı sağlayıcılarınız üzerinden gerçekleşen tüm kullanımdan, ücretlerden, istemlerden, çıktılardan ve sonuçlardan siz sorumlusunuz."] },
      { title: "4. Yapay zekâ çıktısı ve mesleki değerlendirme", body: ["Aurict; yapay zekâ modelleri kullanarak teknik talimatlar üretebilir, dönüştürebilir, özetleyebilir veya çalıştırabilir. Çıktılar eksik, hatalı, güvensiz, güncel olmayan veya kullanım amacınıza uygunsuz olabilir.", "Çıktılara güvenmeden önce bunları incelemek, test etmek, doğrulamak ve onaylamak sizin sorumluluğunuzdadır.", "Aurict hukuki, tıbbi, finansal, uyumlulukla ilgili veya mesleki tavsiye vermez."] },
      { title: "5. Güvenlik ve siber güvenlik özellikleri", body: ["Aurict güvenlik analizi, kod inceleme, sandbox çalıştırma, komut sınıflandırma, MCP entegrasyonları, tarayıcı iş akışları ve isteğe bağlı siber güvenlik araçları içerebilir.", "Bu özellikleri yalnızca sahibi olduğunuz veya test etmek için açıkça yetkilendirildiğiniz sistemlerde, hesaplarda, ağlarda, depolarda, cihazlarda ya da hedeflerde kullanabilirsiniz.", "Aurict'i yetkisiz erişim, kimlik bilgisi hırsızlığı, kötü amaçlı yazılım, kalıcılık, kaçınma, veri sızdırma, taciz, kötüye kullanım veya hukuka aykırı herhangi bir faaliyet için kullanmamalısınız."] },
      { title: "6. Hesaplar, cihaz girişi ve erişim", body: ["Aurict hesap, kimlik doğrulama, tarayıcı girişi, cihaz onayı veya oturum kontrolü özellikleri sunabilir. Hesabınızı ve cihazlarınızı güvende tutmaktan siz sorumlusunuz.", "Aurict ve depo sahibi; güvenlik, kötüye kullanımı önleme, bakım, yasal uyumluluk veya ürün yönü için gerekli olduğunda barındırılan özelliklere erişimi kısıtlayabilir, askıya alabilir, geri alabilir, değiştirebilir veya sonlandırabilir."] },
      { title: "7. Veri uygulamaları değişebilir", body: ["Aurict, herkese açık web sitesi veya açık kaynak CLI üzerinden varsayılan olarak ürün telemetrisi, sohbet içeriği, depo içeriği, istemler, üretilmiş dosyalar veya API anahtarları toplamayı şu anda amaçlamaz.", "Bu durum gelecekte değişebilir. Aurict; hesap, faturalama, telemetri, çökme raporlama, analitik, güvenlik, sahteciliği önleme, kötüye kullanımı önleme veya ürün işletimi için veri toplama ekleyebilir.", "Gelecekteki kullanım; güncellenmiş gizlilik koşullarına, rıza akışlarına, bildirimlere, yapılandırma seçeneklerine veya sağlayıcıya özgü gereksinimlere tabi olabilir."] },
      { title: "8. Bu Koşullardaki değişiklikler", body: ["Aurict ve depo sahibi bu Koşulları dilediği anda güncelleme, değiştirme, genişletme, daraltma, askıya alma veya kaldırma hakkını saklı tutar.", "Değişiklikler web sitesinde, depoda, sürüm notlarında veya makul başka kanallarda yayımlanabilir. Değişiklikler yayımlandıktan sonra kullanımın sürdürülmesi, hukukun izin verdiği yerde güncellenmiş Koşulları kabul olarak değerlendirilebilir."] },
      { title: "9. Feragat ve sorumluluğun sınırlandırılması", body: ["Aurict, hukukun izin verdiği azami ölçüde, herhangi bir türde garanti olmaksızın olduğu gibi ve mevcut haliyle sunulur.", "Aurict, depo sahibi, bakımcılar, katkıda bulunanlar ve ilgili taraflar; Aurict kullanımınızdan doğan kâr kaybı, veri kaybı, sağlayıcı ücretleri, güvenlik olayları, iş kesintisi, model hataları, yetkisiz kullanım veya dolaylı, arızi, özel, sonuçsal ya da cezai zararlardan sorumlu değildir."] },
    ],
  },
}

export function getLegalPage(page: "privacy" | "terms", locale: AppLocale): LegalPage {
  if (locale === "tr") return page === "privacy" ? privacy.tr : terms.tr
  const source = page === "privacy" ? privacy.en : terms.en
  return localizeEnglishContent(locale, source)
}
